allowBuilds:
  '@carbon/icon-helpers': false
  '@carbon/icons': false
  'esbuild': false
  'unrs-resolver': false

catalog:
  '@carbon/icons': 11.85.0
  '@chromatic-com/storybook': 5.3.0
  '@react-native-async-storage/async-storage': 2.2.0
  '@react-native-community/datetimepicker': 8.4.4
  '@storybook/addon-docs': 10.5.7
  '@storybook/addon-ondevice-actions': 10.5.4
  '@storybook/addon-ondevice-backgrounds': 10.5.4
  '@storybook/addon-ondevice-controls': 10.5.4
  '@storybook/addon-ondevice-notes': 10.5.4
  '@storybook/react': 10.5.7
  '@storybook/react-native': 10.5.4
  '@storybook/react-native-web-vite': 10.5.7
  'react-native-builder-bob': 0.43.0
  'react-native-safe-area-context': 5.7.0
  'react-native-svg': 15.15.5
  'storybook': 10.5.7

engineStrict: true

minimumReleaseAgeExclude:
  - globals@17.10.0

nodeLinker: hoisted

packages:
  - 'packages/*'
  - 'packages-builder/*'
  - 'storybook/*'
