const code = require('../code.json')
const hexToRgba = require('../../../helpers/color/hex-to-rgba')

/**
 * Sorry, for using snake case here, while the code.json is using camelCase, and the index.js is using upper snake_case
 */

module.exports = {

	background: code.black,
	background_hover: hexToRgba(code.gray50, '0.16'),
	background_active: hexToRgba(code.gray50, '0.4'),
	background_selected: hexToRgba(code.gray50, '0.24'),
	background_selected_hover: hexToRgba(code.gray50, '0.32'),
	background_inverse: code.gray10,
	background_inverse_hover: code.gray10Hover,
	background_brand: code.blue60,

	layer_01: code.gray90,
	layer_02: code.gray80,
	layer_03: code.gray70,
	layer_hover_01: code.gray90Hover,
	layer_hover_02: code.gray80Hover,
	layer_hover_03: code.gray70Hover,
	layer_active_01: code.gray70,
	layer_active_02: code.gray60,
	layer_active_03: code.gray50,
	layer_selected_01: code.gray80,
	layer_selected_02: code.gray70,
	layer_selected_03: code.gray60,
	layer_selected_hover_01: code.gray80Hover,
	layer_selected_hover_02: code.gray70Hover,
	layer_selected_hover_03: code.gray60Hover,
	layer_selected_inverse: code.gray10,
	layer_selected_disabled: code.gray60,

	layer_accent_01: code.gray80,
	layer_accent_02: code.gray70,
	layer_accent_03: code.gray60,
	layer_accent_hover_01: code.gray80Hover,
	layer_accent_hover_02: code.gray70Hover,
	layer_accent_hover_03: code.gray60Hover,
	layer_accent_active_01: code.gray70,
	layer_accent_active_02: code.gray50,
	layer_accent_active_03: code.gray80,

	field_01: code.gray90,
	field_02: code.gray80,
	field_03: code.gray70,
	field_hover_01: code.gray90Hover,
	field_hover_02: code.gray80Hover,
	field_hover_03: code.gray70Hover,

	border_interactive: code.blue50,
	border_subtle_00: code.gray80,
	border_subtle_01: code.gray80,
	border_subtle_02: code.gray70,
	border_subtle_03: code.gray60,
	border_subtle_selected_01: code.gray70,
	border_subtle_selected_02: code.gray60,
	border_subtle_selected_03: code.gray50,
	border_strong_01: code.gray60,
	border_strong_02: code.gray50,
	border_strong_03: code.gray40,
	border_tile_01: code.gray70,
	border_tile_02: code.gray60,
	border_tile_03: code.gray50,
	border_inverse: code.gray10,
	border_disabled: hexToRgba(code.gray50, '0.5'),

	text_primary: code.gray10,
	text_secondary: code.gray30,
	text_placeholder: code.gray60,
	text_on_color: code.white,
	text_on_color_disabled: hexToRgba(code.white, '0.25'),
	text_helper: code.gray50,
	text_error: code.red40,
	text_inverse: code.gray100,
	text_disabled: hexToRgba(code.gray10, '0.25'),

	link_primary: code.blue40,
	link_primary_hover: code.blue30,
	link_secondary: code.blue30,
	link_inverse: code.blue60,
	link_inverse_hover: code.blue70,
	link_inverse_active: code.gray100,
	link_inverse_visited: code.purple60,
	link_visited: code.purple40,

	icon_primary: code.gray10,
	icon_secondary: code.gray30,
	icon_on_color: code.white,
	icon_on_color_disabled: hexToRgba(code.white, '0.25'),
	icon_interactive: code.white,
	icon_inverse: code.gray100,
	icon_disabled: hexToRgba(code.gray10, '0.25'),

	support_error: code.red50,
	support_success: code.green40,
	support_warning: code.yellow30,
	support_info: code.blue50,
	support_error_inverse: code.red60,
	support_success_inverse: code.green50,
	support_warning_inverse: code.yellow30,
	support_info_inverse: code.blue70,
	support_caution_minor: code.yellow30,
	support_caution_major: code.orange40,
	support_caution_undefined: code.purple50,

	focus: code.white,
	focus_inset: code.gray100,
	focus_inverse: code.blue60,

	interactive: code.blue50,
	highlight: code.blue90,
	toggle_off: code.gray60,
	overlay: hexToRgba(code.gray100, '0.7'),
	skeleton_element: code.gray70,
	skeleton_background: code.gray80Hover,

	button_primary: code.blue60,
	button_primary_hover: code.blue60Hover,
	button_primary_active: code.blue80,
	button_secondary: code.gray60,
	button_secondary_hover: code.gray60Hover,
	button_secondary_active: code.gray80,
	button_tertiary: code.white,
	button_tertiary_hover: code.gray10,
	button_tertiary_active: code.gray30,
	button_danger_primary: code.red60,
	button_danger_secondary: code.red50,
	button_danger_hover: code.red60Hover,
	button_danger_active: code.red80,
	button_separator: code.gray100,
	button_disabled: code.gray70,

	tag_background_gray: code.gray70,
	tag_color_gray: code.gray20,
	tag_hover_gray: code.gray70Hover,
	tag_border_gray: code.gray50,
	tag_background_cool_gray: code.coolGray70,
	tag_color_cool_gray: code.coolGray20,
	tag_hover_cool_gray: code.coolGray70Hover,
	tag_border_cool_gray: code.coolGray50,
	tag_background_warm_gray: code.warmGray70,
	tag_color_warm_gray: code.warmGray20,
	tag_hover_warm_gray: code.warmGray70Hover,
	tag_border_warm_gray: code.warmGray50,
	tag_background_red: code.red70,
	tag_color_red: code.red20,
	tag_hover_red: code.red70Hover,
	tag_border_red: code.red50,
	tag_background_magenta: code.magenta70,
	tag_color_magenta: code.magenta20,
	tag_hover_magenta: code.magenta70Hover,
	tag_border_magenta: code.magenta50,
	tag_background_purple: code.purple70,
	tag_color_purple: code.purple20,
	tag_hover_purple: code.purple70Hover,
	tag_border_purple: code.purple50,
	tag_background_blue: code.blue70,
	tag_color_blue: code.blue20,
	tag_hover_blue: code.blue70Hover,
	tag_border_blue: code.blue50,
	tag_background_cyan: code.cyan70,
	tag_color_cyan: code.cyan20,
	tag_hover_cyan: code.cyan70Hover,
	tag_border_cyan: code.cyan50,
	tag_background_teal: code.teal70,
	tag_color_teal: code.teal20,
	tag_hover_teal: code.teal70Hover,
	tag_border_teal: code.teal50,
	tag_background_green: code.green70,
	tag_color_green: code.green20,
	tag_hover_green: code.green70Hover,
	tag_border_green: code.green50,

	notification_background_error: code.gray90,
	notification_background_success: code.gray90,
	notification_background_info: code.gray90,
	notification_background_warning: code.gray90,
	notification_action_hover: code.gray90Hover,
	notification_action_tertiary_inverse: code.blue60,
	notification_action_tertiary_inverse_active: code.gray100,
	notification_action_tertiary_inverse_hover: code.blue80,
	notification_action_tertiary_inverse_text: code.white,
	notification_action_tertiary_inverse_text_on_color_disabled: code.white,

}
