import {
	hexToRgba,
} from '../../../helpers/color/hex-to-rgba'

import type {
	ThemeType,
} from '../../../types'

import code from '../code.json'

export const gray_10 = {

	background: code.gray10,
	background_hover: hexToRgba(code.gray50, '0.12'),
	background_active: hexToRgba(code.gray50, '0.5'),
	background_selected: hexToRgba(code.gray50, '0.2'),
	background_selected_hover: hexToRgba(code.gray50, '0.32'),
	background_inverse: code.gray80,
	background_inverse_hover: code.gray80Hover,
	background_brand: code.blue60,

	layer_01: code.white,
	layer_02: code.gray10,
	layer_03: code.white,
	layer_hover_01: code.gray10Hover,
	layer_hover_02: code.gray10Hover,
	layer_hover_03: code.gray10Hover,
	layer_active_01: code.gray30,
	layer_active_02: code.gray30,
	layer_active_03: code.gray30,
	layer_selected_01: code.gray20,
	layer_selected_02: code.gray20,
	layer_selected_03: code.gray20,
	layer_selected_hover_01: code.gray20Hover,
	layer_selected_hover_02: code.gray20Hover,
	layer_selected_hover_03: code.gray20Hover,
	layer_selected_inverse: code.gray100,
	layer_selected_disabled: code.gray50,

	layer_accent_01: code.gray20,
	layer_accent_02: code.gray20,
	layer_accent_03: code.gray20,
	layer_accent_hover_01: code.gray20Hover,
	layer_accent_hover_02: code.gray20Hover,
	layer_accent_hover_03: code.gray20Hover,
	layer_accent_active_01: code.gray40,
	layer_accent_active_02: code.gray40,
	layer_accent_active_03: code.gray40,

	field_01: code.white,
	field_02: code.gray10,
	field_03: code.white,
	field_hover_01: code.gray10Hover,
	field_hover_02: code.gray10Hover,
	field_hover_03: code.gray10Hover,

	border_interactive: code.blue60,
	border_subtle_00: code.gray30,
	border_subtle_01: code.gray20,
	border_subtle_02: code.gray30,
	border_subtle_03: code.gray20,
	border_subtle_selected_01: code.gray30,
	border_subtle_selected_02: code.gray30,
	border_subtle_selected_03: code.gray30,
	border_strong_01: code.gray50,
	border_strong_02: code.gray50,
	border_strong_03: code.gray50,
	border_tile_01: code.gray40,
	border_tile_02: code.gray30,
	border_tile_03: code.gray40,
	border_inverse: code.gray100,
	border_disabled: code.gray30,

	text_primary: code.gray100,
	text_secondary: code.gray70,
	text_placeholder: code.gray40,
	text_on_color: code.white,
	text_on_color_disabled: code.gray50,
	text_helper: code.gray60,
	text_error: code.red60,
	text_inverse: code.white,
	text_disabled: hexToRgba(code.gray100, '0.25'),

	link_primary: code.blue60,
	link_primary_hover: code.blue70,
	link_secondary: code.blue70,
	link_inverse: code.blue40,
	link_inverse_hover: code.blue30,
	link_inverse_active: code.gray10,
	link_inverse_visited: code.purple40,
	link_visited: code.purple60,

	icon_primary: code.gray100,
	icon_secondary: code.gray70,
	icon_on_color: code.white,
	icon_on_color_disabled: code.gray50,
	icon_interactive: code.blue60,
	icon_inverse: code.white,
	icon_disabled: hexToRgba(code.gray100, '0.25'),

	support_error: code.red60,
	support_success: code.green50,
	support_warning: code.yellow30,
	support_info: code.blue70,
	support_error_inverse: code.red50,
	support_success_inverse: code.green40,
	support_warning_inverse: code.yellow30,
	support_info_inverse: code.blue50,
	support_caution_minor: code.yellow30,
	support_caution_major: code.orange40,
	support_caution_undefined: code.purple60,

	focus: code.blue60,
	focus_inset: code.white,
	focus_inverse: code.white,

	interactive: code.blue60,
	highlight: code.blue20,
	toggle_off: code.gray50,
	overlay: hexToRgba(code.gray100, '0.5'),
	skeleton_element: code.gray30,
	skeleton_background: code.gray10Hover,

	button_primary: code.blue60,
	button_primary_hover: code.blue60Hover,
	button_primary_active: code.blue80,
	button_secondary: code.gray80,
	button_secondary_hover: code.gray80Hover,
	button_secondary_active: code.gray60,
	button_tertiary: code.blue60,
	button_tertiary_hover: code.blue60Hover,
	button_tertiary_active: code.blue80,
	button_danger_primary: code.red60,
	button_danger_secondary: code.red60,
	button_danger_hover: code.red60Hover,
	button_danger_active: code.red80,
	button_separator: code.gray20,
	button_disabled: code.gray30,

	tag_background_gray: code.gray20,
	tag_color_gray: code.gray100,
	tag_hover_gray: code.gray20Hover,
	tag_border_gray: code.gray40,
	tag_background_cool_gray: code.coolGray20,
	tag_color_cool_gray: code.coolGray100,
	tag_hover_cool_gray: code.coolGray20Hover,
	tag_border_cool_gray: code.coolGray40,
	tag_background_warm_gray: code.warmGray20,
	tag_color_warm_gray: code.warmGray100,
	tag_hover_warm_gray: code.warmGray20Hover,
	tag_border_warm_gray: code.warmGray40,
	tag_background_red: code.red20,
	tag_color_red: code.red70,
	tag_hover_red: code.red20Hover,
	tag_border_red: code.red40,
	tag_background_magenta: code.magenta20,
	tag_color_magenta: code.magenta70,
	tag_hover_magenta: code.magenta20Hover,
	tag_border_magenta: code.magenta40,
	tag_background_purple: code.purple20,
	tag_color_purple: code.purple70,
	tag_hover_purple: code.purple20Hover,
	tag_border_purple: code.purple40,
	tag_background_blue: code.blue20,
	tag_color_blue: code.blue70,
	tag_hover_blue: code.blue20Hover,
	tag_border_blue: code.blue40,
	tag_background_cyan: code.cyan20,
	tag_color_cyan: code.cyan70,
	tag_hover_cyan: code.cyan20Hover,
	tag_border_cyan: code.cyan40,
	tag_background_teal: code.teal20,
	tag_color_teal: code.teal70,
	tag_hover_teal: code.teal20Hover,
	tag_border_teal: code.teal40,
	tag_background_green: code.green20,
	tag_color_green: code.green70,
	tag_hover_green: code.green20Hover,
	tag_border_green: code.green40,

	notification_info_background: code.blue10,
	notification_info_border: hexToRgba(code.blue70, '0.3'),
	notification_error_background: code.red10,
	notification_error_border: hexToRgba(code.red60, '0.3'),
	notification_success_background: code.green10,
	notification_success_border: hexToRgba(code.green50, '0.3'),
	notification_warning_background: code.yellow10,
	notification_warning_border: hexToRgba(code.yellow30, '0.3'),

	notification_action_hover: code.white,
	notification_action_tertiary_inverse: code.white,
	notification_action_tertiary_inverse_active: code.white,
	notification_action_tertiary_inverse_hover: code.gray30,
	notification_action_tertiary_inverse_text: code.gray100,
	notification_action_tertiary_inverse_text_on_color_disabled: code.white,

} as const satisfies Record<ThemeType.ColorToken, string>
