export const FontFamily = {
	thin: 'IBMPlexSans-Thin',
	thin_italic: 'IBMPlexSans-Thin-Italic',
	extralight: 'IBMPlexSans-ExtraLight',
	extralight_italic: 'IBMPlexSans-ExtraLight-Italic',
	light: 'IBMPlexSans-Light',
	light_italic: 'IBMPlexSans-Light-Italic',
	normal: 'IBMPlexSans-Regular',
	normal_italic: 'IBMPlexSans-Regular-Italic',
	medium: 'IBMPlexSans-Medium-Italic',
	medium_italic: 'IBMPlexSans-Medium-Italic',
	semibold: 'IBMPlexSans-SemiBold',
	semibold_italic: 'IBMPlexSans-SemiBold-Italic',
	bold: 'IBMPlexSans-Bold',
	bold_italic: 'IBMPlexSans-Italic',
} as const
