/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* do not change this file, it is auto generated by storybook. */
import { start, updateView, View } from '@storybook/react-native';

import "@storybook/addon-ondevice-notes/register";
import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-backgrounds/register";
import "@storybook/addon-ondevice-actions/register";

const normalizedStories = [
	{
		titlePrefix: "",
		directory: "./src/stories",
		files: "**/*.stories.?(ts|tsx)",
		importPathMatcher: /^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(?:ts|tsx)?)$/,
		// @ts-expect-error React Native configurations
		req: require.context(
			'../src/stories',
			true,
			/^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(?:ts|tsx)?)$/,
		),
	},
];


declare global {
	const view: View;
	const STORIES: typeof normalizedStories;
}


const annotations = [
	require('./preview'),
	require("@storybook/react-native/preview"),
];

// @ts-expect-error React Native Configurations
global.STORIES = normalizedStories;

// @ts-expect-error React Native Configurations
module?.hot?.accept?.();

// @ts-expect-error React Native Configurations
if(!global.view) {
	// @ts-expect-error React Native Configurations
	global.view = start({
		annotations,
		storyEntries: normalizedStories,

	});
} else {
	// @ts-expect-error React Native Configurations
	updateView(global.view, annotations, normalizedStories);
}

// @ts-expect-error React Native Configurations
export const view: View = global.view;
