name: Deploy Storybook

on:
  push:
    branches:
      - deploy-storybook

jobs:
  deploy-storybook:
    name: Deploy Storybook to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Use PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 10
          cache: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - name: Init IBM Fonts to Storybook Web
        run: npm run init-ibm-fonts-storybook-web
      - name: Deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install --frozen-lockfile
          build_command: npm run packages-builder:carbon-react-native-elements && npm run packages-builder:carbon-react-native && npm run storybook-build
          path: ./storybook/.dist
          checkout: false
