name: Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      # Required NPM >= 11.5.1 for Trusted Publishing (OIDC)
      - name: 'Update NPM version'
        run: npm install -g npm@latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Validate Color Token
        run: npm run validate-color-token
      - name: Build carbon-react-native-elements
        run: |
          npm run prepack-carbon-react-native-elements
          npm run builder-bob carbon-react-native-elements
      - name: Build carbon-react-native
        run: |
          npm run prepack-carbon-react-native
          npm run builder-bob carbon-react-native
      - name: Code check
        run: npm run code-check
      - name: Release to npm registry
        run: |
          pnpm publish --filter @audira/carbon-react-native-elements --access public --no-git-checks
          pnpm publish --filter @audira/carbon-react-native --access public --no-git-checks
