name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    environment: test-build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Use PNPM
        uses: pnpm/action-setup@v6
        with:
          # temporarily stick to the 11.11.0 because 11.12.0 has issue in Action
          # https://github.com/pnpm/action-setup/issues/276
          version: 11.11.0
          cache: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Validate Color Token
        run: npm run validate-color-token
      - name: Build carbon-react-native-elements
        run: npm run packages-builder:carbon-react-native-elements
      - name: Build carbon-react-native
        run: npm run packages-builder:carbon-react-native
      - name: Build Storybook
        run: |
          npm run init-ibm-fonts-storybook-web
          npm run storybook-build
      - name: Type Check and Lint Check
        run: npm run code-check
